[default] 
root_dir = /home/ubuntu/experiments 
data_dir = %(root_dir)s/data
plots_dir  = %(data_dir)s/plots
results_dir = %(data_dir)s/results
dataset_dir = %(data_dir)s/datasets
plots_dir = %(data_dir)s/plots
credentials = /Users/sarahwooders/repos/experiments/ralf-vldb.json
aws_dir = vldb
aws_bucket = feature-store-datasets
