[default] 
root_dir = /Users/sarahwooders/repos/experiments 
data_dir = %(root_dir)s/data
plots_dir  = %(data_dir)s/plots
results_dir = %(data_dir)s/results
dataset_dir = %(data_dir)s/datasets
credentials = %(root_dir)s/ralf-vldb.json
aws_dir = vldb
aws_bucket = feature-store-datasets
