[default]
# root_dir = .
results_dir = results
dataset_dir = datasets
# credentials = /home/eecs/wooders/experiments/ralf-vldb.json
credentials = aws.json
aws_dir = vldb
aws_bucket = feature-store-datasets
