[default] 
root_dir = /home/eecs/jeffcheng1234/experiments
data_dir = /data/jeffcheng1234/ralf-vldb/
results_dir = %(data_dir)s/results
plots_dir = %(data_dir)s/plots
dataset_dir = %(data_dir)s/datasets
credentials = %(root_dir)s/ralf-vldb.json
aws_dir = vldb
aws_bucket = feature-store-datasets
