[directory]
data_dir = /data/wooders/wikipedia
revisions_dir = %(data_dir)s/recentchanges
raw_doc_dir = %(data_dir)s/doc_xml/
parsed_doc_dir = %(data_dir)s/doc_pkl/
parsed_tmp_dir = %(data_dir)s/parsed_tmp/
diff_dir = %(data_dir)s/diffs/
embedding_dir = %(data_dir)s/embeddings/

[files]
data_dir = /data/wooders/wikipedia
raw_questions_file = %(data_dir)s/10052021_questions_revid.csv 
model_file = %(data_dir)s/bert-base-encoder.cp
changes_file = %(data_dir)s/changes.csv
titles_file = %(data_dir)s/top_titles.csv
revisions_file = %(data_dir)s/title_revisions_timestamps.json
edits_file = %(data_dir)s/edits.csv 
questions_file = %(data_dir)s/questions.csv
pageview_file = %(data_dir)s/top_title_views.csv

[simulation]
data_dir = /data/wooders/wikipedia
plan_dir = /data/wooders/wiki-plans
init_data_file = %(data_dir)s/init_data.json
stream_edits_file = %(data_dir)s/edit_stream.json
stream_questions_file = %(data_dir)s/question_stream.json


